[workspace]
authors = ["Axel Donath <axel.donath@cfa.harvard.edu>"]
channels = ["conda-forge"]
name = "from-scratch-in-jax-nano-gpt"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[activation.env]
JAX_TRACEBACK_FILTERING="off"
JAX_COMPILATION_CACHE_DIR=".jax_cache"

[dependencies]
safetensors = ">=0.5.3,<0.6"
python = ">=3.12.11,<3.14"
requests = ">=2.32.4,<3"
tiktoken = ">=0.9.0,<0.10"
tqdm = ">=4.67.1,<5"
wandb = ">=0.20.0,<0.22"
tyro = ">=0.9.26,<0.10"
optax = ">=0.2.4,<0.3"

[pypi-dependencies]
tomli-w = ">=1.2.0, <2"
clouseau = { git = "https://github.com/adonath/clouseau.git", branch = "main" }

[system-requirements]
cuda = "12"

[feature.cpu.dependencies]
jax = ">=0.5.0,<0.7"

[feature.gpu.activation.env]
JAX_DEFAULT_MATMUL_PRECISION="float32"

[feature.gpu.target.linux-64.pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }

[feature.gpu-mps.target.osx-arm64.pypi-dependencies]
jax = ">=0.5.0"
jax-metal = ">=0.0.7"

[feature.gpu-mps.activation.env]
JAX_ENABLE_X64="0"
ENABLE_PJRT_COMPATIBILITY="1"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
gpu-mps = ["gpu-mps"]
