[workspace]
authors = ["Axel Donath <mail@axeldonath.com>"]
channels = ["conda-forge"]
name = "nanogptx"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
download = {cmd=["python", "src/download.py"]}
prepare = {cmd=["python", "src/prepare.py"]}
train = {cmd=["python", "src/train.py"]}
sample = {cmd=["python", "src/sample.py"]}


[dependencies]
python = ">=3.12.11,<3.14"
tqdm = ">=4.67.1,<5"
tyro = ">=0.9.31,<0.10"
tiktoken = ">=0.11.0,<0.12"
safetensors = ">=0.6.2,<0.7"
numpy = ">=2.3.2,<3"
requests = ">=2.32.5,<3"

[pypi-dependencies]
tomli-w = ">=1.2.0, <2"
dacite = ">=1.9.2, <2"

[feature.io.dependencies]
fastparquet = ">=2024.11.0,<2025"
pandas = ">=2.2.3,<3"
zstandard = "*"


[feature.train.dependencies]
wandb = ">=0.21.0,<0.22"


[feature.train.activation.env]
JAX_TRACEBACK_FILTERING="off"
JAX_COMPILATION_CACHE_DIR=".jax_cache"
XLA_PYTHON_CLIENT_MEM_FRACTION="0.75"
WANDB_API_KEY = "$WANDB_API_KEY"


[feature.cpu.dependencies]
optax = ">=0.2.5,<0.3"
jax = ">=0.5.0,<0.7"

[feature.cpu.activation.env]
XLA_FLAGS = '--xla_force_host_platform_device_count=8' # useful for development of shardecd code

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.activation.env]
JAX_DEFAULT_MATMUL_PRECISION="bfloat16"

[feature.gpu.target.linux-64.pypi-dependencies]
optax = ">=0.2.5,<0.3"
jax = { version = ">=0.5.0, <0.8", extras = ["cuda12"] }

[feature.gpu-mps.target.osx-arm64.pypi-dependencies]
optax = ">=0.1.8,<0.3"
jax = "==0.5.0"
jax-metal = ">=0.0.7"

[feature.gpu-mps.activation.env]
JAX_ENABLE_X64="0"
ENABLE_PJRT_COMPATIBILITY="1"


[feature.notebook.dependencies]
notebook = ">=7.1.4,<8"

[feature.profile.dependencies]
tensorflow = "==2.18.0"
tensorboard = ">=2.18.0,<3"

[feature.profile.pypi-dependencies]
xprof = "*"
importlib-resources = ">=6.5.2, <7"


[environments]
prepare = ["io"]
cpu = ["cpu", "train"]
cpu-profile = ["cpu", "train", "profile"]
gpu = ["gpu", "train"]
gpu-profile = ["gpu", "train", "profile"]
gpu-mps = ["gpu-mps",  "train"]
notebook = ["notebook", "cpu", "io", "train"]
