[workspace]
authors = ["Axel Donath <axel.donath@cfa.harvard.edu>"]
channels = ["conda-forge"]
name = "from-scratch-in-jax-nano-gpt"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jax = ">=0.6.0,<0.7"
safetensors = ">=0.5.3,<0.6"
python = ">=3.13.5,<3.14"
requests = ">=2.32.4,<3"
tiktoken = ">=0.9.0,<0.10"
tqdm = ">=4.67.1,<5"
wandb = ">=0.21.0,<0.22"

[pypi-dependencies]
tomli-w = ">=1.2.0, <2"

[system-requirements]
cuda = "12"

[feature.cpu.dependencies]
jax = ">=0.6.0,<0.7"

[feature.gpu.target.linux-64.pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
