[training]
eval_interval = 2000
eval_iters = 1

[training.optimizer]
max_iters = 100

[loading]
batch_size = 8

[loading.index]
dataset = "shakespeare"

[model]
block_size = 64
n_layer = 4
n_head = 4
n_embd = 64
dropout_rate = 0.0
