name: Run download, train and sample Shakespeare

on:
  push:
    branches:
      - main

jobs:
  setup-pixi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Show pixi version
        run: pixi --version

      - name: Run scripts for testing
        run: |
            pixi run download --dataset shakespeare
            pixi run prepare --dataset shakespeare --encoding char --shard-size 1000000 --shards-val 1 --n-process 1 --no-show-progress
            pixi run train train-shakespeare-char --training.optimizer.max-iters 5
            pixi run sample --init-from resume --sampler.max-new-tokens 100 --sampler.num-samples 1
